# flake8: noqa
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017

MYSQL_HOST = 'localhost'
MYSQL_USER = 'root'
MYSQL_PASSWORD = ''
MYSQL_DB = 'seal'

SECRET_KEY = 'secret'
DEBUG = False

SSO_DOMAIN = ''
BROKER_CODE = ''


TWITTER_API_KEY = ''
GOOGLE_API_KEY = ''
AWS_ACCESS_KEY = ""
AWS_SECRET_ACCESS_KEY = ""
